# Netlify Configuration for MarketingBy Frontend

[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite default output)
  publish = "dist"
  
  # Build environment variables
  [build.environment]
    VITE_API_BASE_URL = "https://marketingby-wetechforu-b67c6bd0bf6b.herokuapp.com/api"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

