repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: gitleaks secret scan
        args: ["protect", "--staged", "--no-banner", "--redact", "--config=.gitleaks.toml"]

