version: '3.8'

services:
  web:
    build: .
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/health_clinic_marketing
      - FLASK_PORT=9000
      - DEBUG=false
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=health_clinic_marketing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
